server:
  port: 8080

spring:
  datasource:
    username: work_order_system
    password: Root1234
    url: jdbc:mysql://rm-wz9ev2rzm1e4s0r7eyo.mysql.rds.aliyuncs.com:3306/workform-system?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active:
      - cookie

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
  mapper-locations:
    - classpath:mapper/*Mapper.xml



