server:
  port: 8080

spring:
  datasource:
    username: your_username
    password: your_password
    url: jdbc:mysql://xxx:3306/xxx?characterEncoding=utf-8&allowMultiQueries=true


    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active:
      - cookie
      - aliyun

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
  mapper-locations:
    - classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      server:
        workordersystem:
          mapper: debug

